"""empty message

Revision ID: 1607c03bf874
Revises: 78c8d4337c2e
Create Date: 2020-01-22 20:20:36.526221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1607c03bf874'
down_revision = '78c8d4337c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
